### ISSUE TITLE
Japanese: Text overflow in the settings UI

### ISSUE THREAD

**Issue by Umichang** [marzent/XIV-on-Mac#110] opened 2023-01-29 00:07 UTC
The HUD option description text is overflowing.

<img width="818" alt="image" src="https://user-images.githubusercontent.com/48762335/215296737-a3724928-95b7-4390-86c1-7d064f856ee6.png">

To address this problem, I need to either make my translation fit by cutting down the text, or have text wrapping enabled.

**Comment by CovertDuck** [comment] 2023-01-29 00:11
The issue is also present in the French localization.

**Comment by marzent** [comment] 2023-01-29 08:25
Fixed with 0fbe4206742c7d1223dc349b283e413bb212b769

**Closed by marzent** 2023-01-29 08:25 UTC
