### ISSUE TITLE
Page fault during installation

### ISSUE THREAD

**Issue by gcruicks** [marzent/XIV-on-Mac#19] opened 2022-01-12 11:00 UTC
Trying to install a fresh copy of the game via XIVLauncher which then crashed with the attached error.

[backtrace.txt](https://github.com/marzent/XIV-on-Mac/files/7854007/backtrace.txt)

```
Unhandled exception: page fault on read access to 0x83482024446f0f6e in 64-bit code (0x000000007b011e0e).
Register dump:
 rip:000000007b011e0e rsp:000000000021cb10 rbp:0000000002062670 eflags:00000202 (   - --  I   - - - )
 rax:000000000021cb50 rbx:00000000035fbcd8 rcx:000000000021cb30 rdx:0000000000000000
 rsi:0000000001791f70 rdi:000000000021cb60  r8:0000000000000002  r9:0000000001791f60 r10:000000001d3cc77e
 r11:000000000021cc70 r12:000000000000c041 r13:0000000000000000 r14:00000000035fbcd8 r15:0000000000000000
Stack dump:
0x000000000021cb10:  000000000021cb30 0000000000000000
0x000000000021cb20:  00000000033387f8 000000000021d090
0x000000000021cb30:  00000000c0000005 0000000000000000
0x000000000021cb40:  000000001d3cc77e 0000000000000002
0x000000000021cb50:  0000000000000000 83482024446f0f6e
0x000000000021cb60:  4054c00000000000 00000000035fbcd8
0x000000000021cb70:  0000000001e26f78 0000000000e41028
0x000000000021cb80:  000000001d3cc77e 0000000000e4527d
0x000000000021cb90:  000000000021cc50 0000000001575370
0x000000000021cba0:  0000000000000000 000000000021cc70
0x000000000021cbb0:  000000001d3cc77e 000000000100ca6a
0x000000000021cbc0:  000000000021cc50 000000000021ee10
Backtrace:
=>0 0x000000007b011e0e format_exception_msg+0x32e(ptr=<is not available>, buffer=<is not available>, size=<is not available>) [Z:\Users\marc_aurel\github\macos-crossover-wine-cloud-builder-main\macos-crossover-wine-cloud-builder\sources\wine\dlls\kernelbase\debug.c:315] in kernelbase (0x0000000002062670)
  1 0x0000000000e41209 EntryPoint+0xffffffffffffffff() in clr (0x0000000002062670)
  2 0x0000000000e4123b EntryPoint+0xffffffffffffffff() in clr (0x0000000002062670)
  3 0x0000000000e41245 EntryPoint+0xffffffffffffffff() in clr (0x0000000002062670)
0x000000007b011e0e format_exception_msg+0x32e [Z:\Users\marc_aurel\github\macos-crossover-wine-cloud-builder-main\macos-crossover-wine-cloud-builder\sources\wine\dlls\kernelbase\debug.c:315] in kernelbase: nop	
Unable to access file 'Z:\Users\marc_aurel\github\macos-crossover-wine-cloud-builder-main\macos-crossover-wine-cloud-builder\sources\wine\dlls\kernelbase\debug.c'
```

Relaunching the installer and starting again, seems to have gotten past the issue.

**Comment by zhang-chengyu** [comment] 2022-01-13 03:03
I had the same issue today when running the xivlauncher and downloading the game files for the first time on a newly reset MacBook Pro 13 M1 (Monterey 12.1). Same thing also happened to me before the reset when I tried XIV on Mac for the first time (mentioned it in the pre-alpha feedback post). Relaunching xivlauncher after the error, it could continue downloading but also may crash without any error message (happened once today, twice last time). Once xivlauncher has finished installing all the game files, completely uninstall XIV on Mac with appcleaner and reinstall (and redownload everything) would no longer have any issue at all. Could it be Rosetta's fault?

**Comment by seathasky** [comment] 2022-01-13 04:14
It seems more common on M1 yes. We're looking into the setup process still and hopefully will have these crashes alleviated in future release of our application. Sorry for the frustration!

**Comment by marzent** [comment] 2022-01-15 22:23
> I had the same issue today when running the xivlauncher and downloading the game files for the first time on a newly reset MacBook Pro 13 M1 (Monterey 12.1). Same thing also happened to me before the reset when I tried XIV on Mac for the first time (mentioned it in the pre-alpha feedback post). Relaunching xivlauncher after the error, it could continue downloading but also may crash without any error message (happened once today, twice last time). Once xivlauncher has finished installing all the game files, completely uninstall XIV on Mac with appcleaner and reinstall (and redownload everything) would no longer have any issue at all. Could it be Rosetta's fault?

Rosetta might definitely behaving weirdly here… Just to clarify these crashes happened during xivlauncher downloading the game and not the .net install @zhang-chengyu ?

@gcruicks Could you describe during which part of the install process it crashed?

**Comment by gcruicks** [comment] 2022-01-15 22:41
> @gcruicks Could you describe during which part of the install process it crashed?

Issue happened while downloading the game files, I think. It’s been a few days, and had a few issues, can’t remember exactly the stage, sorry.

**Comment by marzent** [comment] 2022-01-15 23:33
No worries just trying to document as much as possible, hopefully I can get an M1 based mac soon as well to do some testing on it

**Comment by zhang-chengyu** [comment] 2022-01-16 20:35
> > I had the same issue today when running the xivlauncher and downloading the game files for the first time on a newly reset MacBook Pro 13 M1 (Monterey 12.1). Same thing also happened to me before the reset when I tried XIV on Mac for the first time (mentioned it in the pre-alpha feedback post). Relaunching xivlauncher after the error, it could continue downloading but also may crash without any error message (happened once today, twice last time). Once xivlauncher has finished installing all the game files, completely uninstall XIV on Mac with appcleaner and reinstall (and redownload everything) would no longer have any issue at all. Could it be Rosetta's fault?
> 
> Rosetta might definitely behaving weirdly here… Just to clarify these crashes happened during xivlauncher downloading the game and not the .net install @zhang-chengyu ?
> 
> @gcruicks Could you describe during which part of the install process it crashed?

Yes, the crashes happened during XIVLauncher was downloading and installing game files. I tried a couple of more times in the past few days and always encountered some crashes. Seems the issue is pretty consistent...

**Comment by marzent** [comment] 2022-01-16 20:52
Were you using ARIA2 or the .net downloader?

**Comment by zhang-chengyu** [comment] 2022-01-16 20:56
Not sure that I follow... I didn't change any settings, everything was as default

**Comment by marzent** [comment] 2022-01-17 16:09
![image](https://user-images.githubusercontent.com/44967463/149803711-f4badd65-e5bf-4b07-8cf9-122a65664bb7.png)
Here is the setting I was talking about, depending on when you installed it might be set to a different value

**Comment by zhang-chengyu** [comment] 2022-01-18 18:19
Just tried a clean install with 2.2.1, the default was set to .Net. After switching to ARIA, no crashes at all! (at least for my attempt today)

**Comment by marzent** [comment] 2022-01-18 22:46
Personally I haven’t had issues with either downloader but I think you are not the only ones who ran into this….

Anyhow on a fresh install the default should be set to aria, so I’m closing the issue

**Closed by marzent** 2022-01-18 22:46 UTC
Labels: bug
